/**
 * `describe_image` — a general-purpose captioning tool for ANY image already
 * in the workspace (not just fresh browser screenshots): screenshots the
 * harness or a repo already contains, dashboard-uploaded images (a follow-up
 * feature), diagrams, design mockups. Schema is a single `path` relative to
 * the workspace root; path safety reuses `resolveWithinWorkspace`'s existing
 * guard (src/tools/executor.ts) rather than re-deriving it.
 *
 * The description is generated by the same cloud vision call as the
 * screenshot auto-captioning (src/vision/describe.ts) and the real token/cost
 * is reported back through `ToolContext.onAuxLlmUsage` so the session's
 * BudgetTracker + usage accounting sees it (see recordAuxLlmUsage in
 * src/engine/loop.ts) — an explicit describe_image call is never invisible
 * spend.
 */

import { constants } from "node:fs"
import { access } from "node:fs/promises"

import type OpenAI from "openai"

import type { ToolContext, ToolResult } from "../engine/types.js"
import { resolveWithinWorkspace } from "../tools/executor.js"
import { describeImage } from "./describe.js"

export const DESCRIBE_IMAGE_NAME = "describe_image"

const DESCRIBE_IMAGE_DESCRIPTION = `Request to describe an image file that already exists in the workspace (PNG/JPEG/WebP/GIF): reads the file and returns a detailed, factual text description generated by a cloud vision model — visible text verbatim, layout, UI element states, colors that carry meaning, and anything that looks visually wrong. This is a one-way image -> text conversion: the description is what reaches the coding model, never the raw image bytes.

Use this when a task references an image already present in the repo/workspace and you need to know what it actually shows (e.g. a screenshot checked into the repo, a diagram, a broken-page capture, a design mockup). Do NOT use it for screenshots you took yourself with browser_action — those are already auto-described in the screenshot result. One describe_image call costs a small real amount of money (an LLM API call); use it deliberately, not speculatively.`

const PATH_PARAMETER_DESCRIPTION = `Path to the image file, relative to the workspace root (e.g. "docs/diagram.png" or ".headlesscode/browser-screenshots/screenshot-2026-08-02T00-00-00-000Z.png").`

export const describeImageTool = {
	type: "function",
	function: {
		name: DESCRIBE_IMAGE_NAME,
		description: DESCRIBE_IMAGE_DESCRIPTION,
		strict: true,
		parameters: {
			type: "object",
			properties: {
				path: {
					type: "string",
					description: PATH_PARAMETER_DESCRIPTION,
				},
			},
			required: ["path"],
			additionalProperties: false,
		},
	},
} satisfies OpenAI.Chat.ChatCompletionTool

function ok(content: string): ToolResult {
	return { content, isError: false }
}

function err(content: string): ToolResult {
	return { content: `[Error] ${content}`, isError: true }
}

export async function describeImageHandler(
	args: Record<string, unknown>,
	ctx: ToolContext,
): Promise<ToolResult> {
	const p = args.path
	if (typeof p !== "string" || p.trim() === "") {
		return err(`describe_image: missing or invalid string argument 'path' (got ${JSON.stringify(p)})`)
	}

	let abs: string
	try {
		abs = resolveWithinWorkspace(ctx.workspaceRoot, p)
	} catch (e) {
		return err(`describe_image: ${e instanceof Error ? e.message : String(e)}`)
	}

	try {
		await access(abs, constants.F_OK)
	} catch {
		return err(`describe_image: no such file: ${p} (resolved to ${abs})`)
	}

	try {
		const { description, usage } = await describeImage(abs)
		ctx.onAuxLlmUsage?.(usage)
		return ok(`describe_image: ${p}\n${description}`)
	} catch (e) {
		return err(`describe_image: ${e instanceof Error ? e.message : String(e)}`)
	}
}
